<?php
namespace common\models;

use Yii;
use yii\web\UploadedFile;
use yii\helpers\ArrayHelper;

/**
 * This is the model class for table "news".
 *
 * @property int $id
 * @property string $title
 * @property string|null $description
 * @property string|null $text
 * @property int|null $status
 * @property string|null $image
 * @property int $created_at
 * @property string|null $seourl
 */
class News extends \yii\db\ActiveRecord
{
    public $tags_array;
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'news';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['title', 'created_at'], 'required'],
            [['description', 'text', 'seourl'], 'string'],
            [['status', 'created_at'], 'integer'],
            [['image'], 'file',
                'extensions' => ['jpg', 'jpeg', 'png', 'gif'],
                'checkExtensionByMimeType' => true,

            ],
            [['title'], 'unique'],
            [['tags_array'], 'safe'],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'title' => 'Title',
            'description' => 'Description',
            'text' => 'Text',
            'status' => 'Status',
            'image' => 'Image',
            'created_at' => 'Created At',
            'seourl' => 'Seourl',
            'tags_array' => 'Tags',
        ];
    }

    public function upload()
    {
        $this->image = UploadedFile::getInstance($this, 'image');
//var_dump($this->image);die;
        if(($this->image)){
            $image_file_name = rand(0, 9999).'.'.$this->image->getExtension();

            $this->image->saveAs( Yii::getAlias('@uploads'). '\\' . $image_file_name);
            $this->image = $image_file_name;

            return $this->image;
        }
        return false;
    }

    public static function getPopNews($days, $limit){
        $time = time() - 86400*$days;
        return self::find()->where(['status' => 1])->andWhere('created_at > '.$time.'')->orderBy(['uniq_reader_counter'=>SORT_DESC ])->asArray()->limit($limit)->all();
    }

    public function getNewsTags(){
        return $this->hasMany(NewsTags::class, ['news_id' => 'id']);
    }

    public function getTags(){
        return $this->hasMany(Tag::class, ['id' => 'tag_id'])->via('newsTags');
    }

    public function afterFind()
    {
        $this->tags_array = $this->tags;
    }

    public function afterSave($insert, $changedAttributes)
    {
        parent::afterSave($insert, $changedAttributes); // TODO: Change the autogenerated stub

        $old_arr = ArrayHelper::map($this->tags, 'id','id');

        if(is_array($this->tags_array)){
            foreach($this->tags_array as $singl_tag){
                if(!in_array($singl_tag, $old_arr)){
                    $model = new NewsTags();
                    $model->news_id = $this->id;
                    $model->tag_id = $singl_tag;
                    $model->save();
                }
                if(isset($old_arr[$singl_tag])){
                    unset($old_arr[$singl_tag]);
                }
            }

            NewsTags::deleteAll(['tag_id'=>$old_arr, 'news_id'=>$this->id]);
        }else{
            NewsTags::deleteAll(['news_id'=>$this->id]);
        }

    }

    public function getTagsAsString(){

        return implode(', ', ArrayHelper::map($this->tags, 'id','tag_name'));
    }

}
