<?php
/**
 * Created by PhpStorm.
 * User: yuser
 * Date: 05.08.2020
 * Time: 22:03
 */

namespace app\components;



use yii\base\Widget;

class FirstWidget extends Widget {
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }
    public function run()
    {
        return $this->render(
            'first'
        );
    }
}