<?php
/**
 * Created by PhpStorm.
 * User: yuser
 * Date: 05.08.2020
 * Time: 20:33
 */

namespace app\components;


use common\models\News;
use yii\base\Widget;

class PopWidget extends Widget{

//    public $days; // days in news select
//    public $limit; //news in block
//    public $popnews;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub

        if ($this->days === null) {
            $this->days = 7;
        }
        if ($this->limit === null) {
            $this->limit = 5;
        }
    }

    public function run()
    {
        return 'Hello';

//        $time = time() - 86400*$this->days;
//        $popnews = News::find()->where(['status' => 1])->andWhere('created_at > '.$time.'')->orderBy(['uniq_reader_counter'=>SORT_DESC ])->asArray()->limit($this->limit)->all();
//        return $this->render(
//            'pop',
//            [
//                'popnews' => $popnews,
//            ]
//        );
    }

}