<?php
/**
 * Created by PhpStorm.
 * User: yuser
 * Date: 05.08.2020
 * Time: 20:33
 */

namespace frontend\widgets;


use common\models\News;
use yii\base\Widget;
use yii\widgets\ListView;

class PopWidget extends Widget{

    public $days; // days in news select
    public $limit; //news in block
    public $popnews;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub

        if ($this->days === null) {
            $this->days = 7;
        }
        if ($this->limit === null) {
            $this->limit = 5;
        }
    }

    public function run()
    {
        $popnews = News::getPopNews($this->days, $this->limit);

        return $this->render(
            'pop',
            [
                'popnews' => $popnews,
            ]
        );
    }

}