<?php
/**
 * Created by PhpStorm.
 * User: yuser
 * Date: 05.08.2020
 * Time: 22:16
 */

namespace frontend\widgets;

use yii\base\Widget;

class SecondWidget extends Widget{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run()
    {
        return 'Hello';
    }
}